// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr8khTPJZ9yBw62NKiWic1NUJ5VAw6LKM',
    appId: '1:419058148719:web:6284319a37028c559ff49a',
    messagingSenderId: '419058148719',
    projectId: 'sospet-ac5bb',
    authDomain: 'sospet-ac5bb.firebaseapp.com',
    storageBucket: 'sospet-ac5bb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDzG858OYRqWDbTfblm9x5Ck_Omsn9i20',
    appId: '1:419058148719:android:3505d7fdf236984a9ff49a',
    messagingSenderId: '419058148719',
    projectId: 'sospet-ac5bb',
    storageBucket: 'sospet-ac5bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJxWwlEdDwMMdmEtE6POy4vfUyjkAHoBo',
    appId: '1:419058148719:ios:860b8bba7d247e209ff49a',
    messagingSenderId: '419058148719',
    projectId: 'sospet-ac5bb',
    storageBucket: 'sospet-ac5bb.firebasestorage.app',
    iosBundleId: 'com.example.sospet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJxWwlEdDwMMdmEtE6POy4vfUyjkAHoBo',
    appId: '1:419058148719:ios:860b8bba7d247e209ff49a',
    messagingSenderId: '419058148719',
    projectId: 'sospet-ac5bb',
    storageBucket: 'sospet-ac5bb.firebasestorage.app',
    iosBundleId: 'com.example.sospet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr8khTPJZ9yBw62NKiWic1NUJ5VAw6LKM',
    appId: '1:419058148719:web:cf6fecbdce1f0fe79ff49a',
    messagingSenderId: '419058148719',
    projectId: 'sospet-ac5bb',
    authDomain: 'sospet-ac5bb.firebaseapp.com',
    storageBucket: 'sospet-ac5bb.firebasestorage.app',
  );
}
